(fix): ten_armed_testbed.py np.float
np.float aliases was originally deprecated in NumPy 1.20
AttributeError: module 'numpy' has no attribute 'float'.
To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.